version: '3.9'
services:
  api:
    build:
      dockerfile: api.Dockerfile
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    build:
      dockerfile: db.Dockerfile
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=conduitdb
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}