name: webapp
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  conduit: ^4.1.8
  yaml: ^3.1.0
  uuid: ^3.0.7
  jaguar_jwt: ^3.0.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.1.8
